/*
 * main.h
 *
 *  Created on: 29.07.2020
 *      Author: mail
 */

#ifndef SRC_APPS_LORAMAC_PERIODIC_UPLINK_LPP_HELTEC_WIFI_LORA_32_V2_MAIN_H_
#define SRC_APPS_LORAMAC_PERIODIC_UPLINK_LPP_HELTEC_WIFI_LORA_32_V2_MAIN_H_



#define ACTIVE_REGION LORAMAC_REGION_EU868

#define LORAMAC_CLASSB_ENABLED


#endif /* SRC_APPS_LORAMAC_PERIODIC_UPLINK_LPP_HELTEC_WIFI_LORA_32_V2_MAIN_H_ */
